const prodIniciales = [
    {
        title: "Grand Theft Auto V", 
        id:0, 
        price:500, 
        rating:"9/10",
        category:"Accion", 
        año:"2013", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2020/05/18/game_cover/459398911589803277.jpg",
        pictureUrl2:'https://s1.gaming-cdn.com/images/products/186/616x353/grand-theft-auto-v-pc-juego-rockstar-cover.jpg?v=1647095361',
        review: "Grand Theft Auto V para PC es un juego de acción y aventuras, el quinto de la serie GTA. Como ya es tradición en los juegos de esta serie, se obtienen puntos mediante la comisión de delitos. El juego alterna entre la narrativa visual y la jugabilidad en tercera y en primera persona. El jugador toma el papel de tres criminales tratando de huir de una determinada agencia del gobierno y cometiendo asaltos. No se elige un solo personaje para jugar, la narrativa del juego salta de un personaje a otro.",
        processor: "Intel Core i5 3470 @ 3.2GHz (4 CPUs) / AMD X8 FX-8350 @ 4GHz (8 CPUs)",
        memory: "8 GB RAM",
        graphics: "NVIDIA GTX 660 2GB / AMD HD 7870 2GB",
        storage: "72 GB available space",
    },

    {
        title: "Red Dead Redemption II", 
        id:1, 
        price:500, 
        rating:"9/10",
        category:"Accion", 
        año:"2019", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2019/10/04/game_cover/625467111570207373.jpg",
        pictureUrl2:'https://s1.gaming-cdn.com/images/products/5679/616x353/red-dead-redemption-2-pc-juego-rockstar-cover.jpg?v=1647026658',
        review: "Red Dead Redemption 2 para PC es un juego de acción y aventuras de mundo abierto en el que el jugador puede vagar libremente. Cuenta algunos elementos en tercera persona, además de otras modalidades de juego en primera persona. El jugador puede cometer crímenes, pero de hacerlo deberá estar preparado para ser perseguido por las fuerzas del orden, ¡quienes estarán dispuestas a hacer valer todo el peso de la ley sobre los delincuentes!",
        processor: "Intel Core i7-4770K / AMD Ryzen 5 1500X",
        memory: "12 GB RAM",
        graphics: "Nvidia GeForce GTX 1060 6GB / AMD Radeon RX 480 4GB",
        storage: "150 GB available space",
    },

    {
        title: "God of War", 
        id:2, 
        price:500, 
        rating:"/10",
        category:"Accion", 
        año:"2022", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2020/09/17/game_cover/479791341600340811.jpg",
        pictureUrl2:'https://s3.gaming-cdn.com/images/products/7325/616x353/god-of-war-pc-juego-steam-cover.jpg?v=1651746257',
        review: "La trama del juego se desarrolla en el contexto de los dioses nórdicos en esta iteración, en lugar de la Antigua Grecia de los juegos originales, y se desarrolla libremente en la Escandinavia medieval en el reino de Midgard, que es el equivalente nórdico de las tierras habitadas por los primeros humanos cuando el mundo aún era joven.",
        processor: "Intel i5-6600k (4 core 3.5 GHz) or AMD Ryzen 5 2400 G (4 core 3.6 GHz)",
        memory: "8 GB RAM",
        graphics: "NVIDIA GTX 1060 (6 GB) or AMD RX 570 (4 GB)",
        storage: "70 GB available space",
    },

    {
        title: "No Man's Sky", 
        id:3, 
        price:500, 
        rating:"/10",
        category:"Accion", 
        año:"2016", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2022/06/23/game_cover/904785361655992339.jpg",
        pictureUrl2:'https://s1.gaming-cdn.com/images/products/414/616x353/no-man-s-sky-pc-juego-steam-cover.jpg?v=1653924485',
        review: "No Man’s Sky para PC es un juego de supervivencia de acción y aventuras, en el que el jugador toma la forma de un humanoide alienígena que aterriza tras estrellarse en un accidente, al que se le suministran los elementos básicos que necesita para sobrevivir, e incluso prosperar.",
        processor: "Intel Core i3",
        memory: "8 GB RAM",
        graphics: "nVidia GTX 480 or AMD Radeon 7870",
        storage: "10 GB available space",
    },

    {
        title: "Assassin's Creed Odyssey", 
        id:4, 
        price:500, 
        rating:"/10",
        category:"Accion", 
        año:"2018", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2019/11/11/game_cover/64888371573505629.jpg",
        pictureUrl2:'https://s2.gaming-cdn.com/images/products/3745/616x353/assassin-s-creed-odyssey-deluxe-edition-xbox-one-xbox-series-x-s-deluxe-edition-xbox-one-xbox-series-x-s-juego-microsoft-store-cover.jpg?v=1657267732',
        review: "Pasa de la marginación a la gloria embarcándote en una odisea para descubrir los secretos de tu pasado y cambiar el destino de la antigua Grecia. Tus decisiones influirán en el devenir de tu odisea. Tu juego puede tener distintos finales gracias al nuevo sistema de diálogos y a las decisiones que tomes. Personaliza tu equipo, el barco y tus habilidades especiales para convertirte en leyenda.",
        processor: "Intel Core i7 3770 a 3.5 GHz or AMD Ryzen 5 1400",
        memory: "8 GB RAM",
        graphics: "AMD Radeon R9 290X or NVIDIA GeForce GTX 970",
        storage: "46 GB available space",
    },

    {
        title: "Farcry 4", 
        id:5, 
        price:500, 
        rating:"/10",
        category:"Fps", 
        año:"2014", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2017/12/28/game_cover/1514448000.jpg",
        pictureUrl2:'https://s1.gaming-cdn.com/images/products/6585/616x353/far-cry-4-gold-edition-gold-edition-pc-juego-ubisoft-connect-cover.jpg?v=1652433258',
        review: "Oculto en la recóndita cordillera del Himalaya se encuentra Kyrat, un país anclado en la tradición y la violencia. Eres Ajay Ghale. Viajarás a Kyrat para cumplir con el último deseo de tu madre, pero una vez allí te verás atrapado en una guerra civil desatada para acabar con el régimen opresivo del dictador Pagan Min. Explora y navega este gigantesco mundo de juego, en el que el peligro y los imprevistos acechan a la vuelta de cualquier esquina. Cada decisión que tomes aquí cuenta, y cada segundo es una historia. Bienvenido a Kyrat.",
        processor: "2.5 GHz Intel Core i5-2400S or 4.0 GHz AMD FX-8350",
        memory: "8 GB RAM",
        graphics: "NVIDIA GeForce GTX 680 or AMD Radeon R9 290X",
        storage: "30 GB available space",
    },

    {
        title: "Overwatch", 
        id:6, 
        price:700, 
        rating:"/10",
        category:"Fps", 
        año:"2016", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2019/09/05/game_cover/974564061567671841.jpg",
        pictureUrl2:'https://s1.gaming-cdn.com/images/products/2208/616x353/overwatch-pc-juego-battle-net-cover.jpg?v=1653562168',
        review: "Cuando los jugadores se conectan a la partida, son puestos en dos equipos de seis junto con otros jugadores. Cada jugador puede elegir de entre un máximo de 30 personajes (en el juego, estos son llamados héroes). Los personajes son excelentes: renderizados individualmente, completados con rasgos de personalidad y peculiaridades físicas que son encantadoras y únicas. Estas peculiaridades pueden incluir una sonrisa atractiva, un mechón de pelo cayendo sobre su rostro, y muchas otras características sutiles pero significativas.",
        processor: "Core i5-670 3.46GHz / Phenom II X4 900e",
        memory: "6 GB RAM",
        graphics: "GeForce GTX 660 / Radeon HD 7950",
        storage: "5 GB available space",
    },

    {
        title: "Counter Strike: GO", 
        id:7, 
        price:500, 
        rating:"/10",
        category:"Fps", 
        año:"2012", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2017/10/20/game_cover/1508454000.jpg",
        pictureUrl2:'https://s1.gaming-cdn.com/images/products/9459/616x353/counter-strike-global-offensive-pc-mac-juego-steam-cover.jpg?v=1644770250',
        review: "Counter Strike: Global Offensive es un juego multijugador de disparos en primera persona y es el cuarto de la franquicia Counter Strike. En este título, jugarás en dos equipos que se enfrentan entre sí para conseguir sus objetivos: terroristas vs contraterroristas.",
        processor: "Intel Core 2 Duo E6600 or AMD Phenom X3 8750",
        memory: "2 GB RAM",
        graphics: "Video card must be 256 MB or more",
        storage: "15 GB available space",
    },

    {
        title: "Payday 2", 
        id:8, 
        price:500, 
        rating:"/10",
        category:"Fps", 
        año:"2013", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2017/11/27/game_cover/1511762400.jpg",
        pictureUrl2:'https://s2.gaming-cdn.com/images/products/223/616x353/payday-2-pc-juego-steam-cover.jpg?v=1647271369',
        review: "Payday 2 para PC es un first person shooter cooperativo en el que el éxito de tu partida depende en gran medida de tus compañeros de equipo. El juego está ambientado en Washington, dos años después de los eventos del primer Payday, y es una secuela bien hecha, que mantiene lo mejor del juego original y mejora cuando es necesario.",
        processor: "2.3 GHz Intel Quad Core Processor",
        memory: "8 GB RAM",
        graphics: "Nvidia & AMD (1GB VRAM)",
        storage: "83 GB available space",
    },

    {
        title: "Call of Duty 2", 
        id:9, 
        price:500, 
        rating:"/10",
        category:"Fps", 
        año:"2005", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2016/11/09/game_cover/1478710800.jpg",
        pictureUrl2:'https://s3.gaming-cdn.com/images/products/5705/616x353/call-of-duty-2-pc-mac-juego-steam-cover.jpg?v=1651504282',
        review: "Call of Duty 2 da un nuevo significado a la intensidad cinematográfica y al caos de la batalla, tal y como se vive a través de los ojos de soldados normales que luchan juntos en conflictos épicos de la II Guerra Mundial. Call of Duty 2, secuela del juego original de 2003 (ganador de más de 80 galardones de Juego del Año), ofrece batallas más colosales, intensas y realistas que nunca antes, gracias al maravilloso apartado visual del nuevo motor COD2.",
        processor: "Intel Core 2 Duo (Dual-Core)",
        memory: "512 MB RAM",
        graphics: "NVIDIA Geforce 7300 or ATI Radeon X1600",
        storage: "4 GB available space",
    },

    {
        title: "World of Warcraft", 
        id:10, 
        price:500, 
        rating:"/10",
        category:"Rpg", 
        año:"2004", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2022/04/20/game_cover/234977551650442993.jpg",
        pictureUrl2:'https://s1.gaming-cdn.com/images/products/10713/616x353/world-of-warcraft-dragonflight-pc-juego-cover.jpg?v=1650458014',
        review: "Los Vuelos de Azeroth han regresado, llamados a defender su ancestral hogar, las Islas Dragón. Rebosante de magia elemental y de las energías vitales de Azeroth, este archipiélago despierta de nuevo. Está en tus manos explorar sus maravillas primordiales y descubrir los olvidados secretos que oculta.",
        processor: "Intel Core™ i7-6700K / AMD Ryzen 7 2700X",
        memory: "8 GB RAM",
        graphics: "NVIDIA GeForce GTX 1080 8 GB or AMD Radeon RX Vega 64",
        storage: "100 GB available space",
    },

    {
        title: "Fallout 4", 
        id:11, 
        price:500, 
        rating:"/10",
        category:"Rpg", 
        año:"2015", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2018/01/10/game_cover/1515596400.jpg",
        pictureUrl2:'https://s3.gaming-cdn.com/images/products/755/616x353/fallout-4-pc-juego-steam-cover.jpg?v=1647341100',
        review: "Fallout 4 para PC es un RPG de acción estilo sandbox altamente personalizable. Si te gustan los juegos estrictos controlados y disciplinados, puede que este título no sea el indicado para ti, ya que tienes la opción de elegir casi todo lo que haces y ves y meterte incluso dentro de ese viejo edificio en desuso ¿O no tan en desuso? En el que parece que no pasa nada.",
        processor: "Intel Core i7 4790 3.6 GHz / AMD FX-9590 4.7 GHz",
        memory: "8 GB RAM",
        graphics: "NVIDIA GTX 780 3GB / AMD Radeon R9 290X 4GB",
        storage: "30 GB available space",
    },

    {
        title: "Horizon: Zero Dawn", 
        id:12, 
        price:500, 
        rating:"/10",
        category:"Rpg", 
        año:"2020", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2020/03/10/game_cover/17414581583854575.jpg",
        pictureUrl2:'https://s2.gaming-cdn.com/images/products/6202/616x353/horizon-zero-dawn-complete-edition-pc-juego-steam-cover.jpg?v=1651566259',
        review: "Horizon Zero Dawn for PC es un RPG de acción en el que controlas a Aloy, una superviviente humana en un paisaje distópico del siglo 31. Los humanos pueden ser raros y el acceso a la tecnología es limitado, pero hay una gran población de criaturas robóticas hostiles (que originalmente fueron creadas por empresas tecnológicas, que luego perdieron el control de ellas).",
        processor: "Intel Core i7-4770K@3.5GHz or Ryzen 5 1500X@3.5GHz",
        memory: "16 GB RAM",
        graphics: "Nvidia GeForce GTX 1060 (6 GB) or AMD Radeon RX 580 (8GB)",
        storage: "100 GB available space",
    },

    {
        title: "Final Fantasy X-X2", 
        id:13, 
        price:500, 
        rating:"/10",
        category:"Rpg", 
        año:"2016", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2016/07/05/game_cover/1467748800.jpg",
        pictureUrl2:'https://s1.gaming-cdn.com/images/products/1440/616x353/final-fantasy-x-x-2-hd-remaster-hd-remaster-pc-juego-steam-cover.jpg?v=1649166298',
        review: "FINAL FANTASY X narra la historia de Tidus, una estrella del blitzbol que se embarca junto a la hermosa invocadora Yuna en una misión para poner fin a la espiral de destrucción que una terrible amenaza conocida como \"Sinh\" ha provocado en el mundo de Spira.",
        processor: "2.4GHz quad-core CPU",
        memory: "2 GB RAM",
        graphics: "NVIDIA Geforce GTX 450 / AMD Radeon HD 5750",
        storage: "40 GB available space",
    },

    {
        title: "The Elder Scrolls V: Skyrim", 
        id:14, 
        price:500, 
        rating:"/10",
        category:"Rpg", 
        año:"2016", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2017/10/01/game_cover/1506848400.jpg",
        pictureUrl2:'https://s1.gaming-cdn.com/images/products/1512/616x353/the-elder-scrolls-v-skyrim-special-edition-special-edition-pc-juego-steam-cover.jpg?v=1645628623',
        review: "Skyrim: Edición Especial para PC es una versión remasterizada del aclamado RPG de acción desarrollado por Bethesda y representa la quinta edición del juego de fantasía. Los juegos de Skyrim (de la serie Elder Scroll) han recibido múltiples premios, y son conocidos por su jugabilidad de mundo abierto, mundos cuidadosamente detallados y libertad para que el jugador dirija la acción y, hasta cierto punto, la historia.",
        processor: "Intel i5-2400/AMD FX-8320",
        memory: "8 GB RAM",
        graphics: "NVIDIA GTX 780 3GB /AMD R9 290 4GB",
        storage: "12 GB available space",
    },

    {
        title: "F1", 
        id:15, 
        price:500, 
        rating:"/10",
        category:"Deportes", 
        año:"2022", 
        pictureUrl:"https://pbs.twimg.com/media/FR1qgMUXsAMLeox.jpg",
        pictureUrl2:'https://s3.gaming-cdn.com/images/products/10550/616x353/f1-22-pc-juego-origin-cover.jpg?v=1656769731',
        review: "F1 22 para PC es el vigésimo tercero, y se rumorea que el último, de la franquicia del querido juego de carreras. Únete a pilotos y coches de todo el mundo para competir en algunos de los circuitos más queridos.",
        processor: "Intel Core i5 9600K or AMD Ryzen 5 2600X",
        memory: "16 GB RAM",
        graphics: "NVIDIA GTX 1660 Ti or AMD RX 590",
        storage: "80 GB available space",
    },

    {
        title: "Fifa 22", 
        id:16, 
        price:500, 
        rating:"/10",
        category:"Deportes", 
        año:"2021", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2021/07/13/game_cover/347646311626170418.jpg",
        pictureUrl2:'https://s3.gaming-cdn.com/images/products/9071/616x353/fifa-22-pc-juego-origin-cover.jpg?v=1644970934',
        review: "FIFA 22 para PC es el trigésimo lanzamiento de la franquicia de la popular serie de videojuegos de simulación de fútbol, ​​que sigue los altibajos en la vida real de jugadores y equipos de todo el mundo, utilizando la captura de movimiento real de los jugadores y combinándola con gráficos y físicas de última generación para que cada juego te deje tan agotado como si lo hubieras jugado de verdad.",
        processor: "Intel i5-3550 @ 3.40GHz or AMD FX 8150 @ 3.6GHz",
        memory: "8 GB RAM",
        graphics: "NVIDIA GeForce GTX 670 or AMD Radeon R9 270X",
        storage: "50 GB available space",
    },

    {
        title: "Forza Horizon 5", 
        id:17, 
        price:500, 
        rating:"/10",
        category:"Deportes", 
        año:"2021", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2021/08/24/game_cover/755583641629831675.jpg",
        pictureUrl2:'https://s2.gaming-cdn.com/images/products/8701/616x353/forza-horizon-5-pc-xbox-one-xbox-series-xs-pc-xbox-one-xbox-series-x-s-juego-microsoft-store-cover.jpg?v=1642425313',
        review: "Forza Horizon 5 para PC es un juego de simulación de carreras ambientado en varios lugares de México. Es el quinto juego de la serie Forza Horizon y el duodécimo juego principal de la franquicia general de Forza.",
        processor: "Intel i5-8400 or AMD Ryzen 5 1500X",
        memory: "16 GB RAM",
        graphics: "NVidia GTX 1070 OR AMD RX 590",
        storage: "110 GB available space",
    },

    {
        title: "NBA 2k22", 
        id:18, 
        price:500, 
        rating:"/10",
        category:"Deportes", 
        año:"2021", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2021/07/15/game_cover/101805761626305377.jpg",
        pictureUrl2:'https://s3.gaming-cdn.com/images/products/9446/616x353/nba-2k22-pc-juego-steam-cover.jpg?v=1652957080',
        review: "NBA 2K22 pone todo el universo del baloncesto a tus pies. Juega a la NBA y la WNBA en entornos realistas contra equipos y jugadores auténticos. Construye tu propio dream team en MyTEAM con las estrellas de hoy y las leyendas de ayer. Emprende tu propio camino profesional en Mi CARRERA y experimenta tu ascenso hasta la NBA.",
        processor: "Intel Core i5-4430 @ 3 GHz or AMD FX-8370 @ 3.4 GHz",
        memory: "8 GB RAM",
        graphics: "NVIDIA GeForce GTX 770 2GB or ATI Radeon R9 270 2GB",
        storage: "110 GB available space",
    },

    {
        title: "Madden NFL 22", 
        id:19, 
        price:500, 
        rating:"/10",
        category:"Deportes", 
        año:"2021", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2021/07/13/game_cover/190099791626186008.jpg",
        pictureUrl2:'https://s1.gaming-cdn.com/images/products/9342/616x353/madden-nfl-22-pc-juego-origin-cover.jpg?v=1632986583',
        review: "Nuevas características de Franchise como gestión del personal, un motor de escenarios mejorado y estrategia semanal. Comparte el progreso del avatar y la clase de jugador entre Face of The Franchise y The Yard con el progreso unificado. Y, por primera vez en MUT, ajusta Superstar X-Factors en el descanso.",
        processor: "FX 8150 @3.6GHz or Core i5-3350 @3.40GHz",
        memory: "12 GB RAM",
        graphics: "Radeon R9 270x or GeForce GTX 680",
        storage: "50 GB available space",
    },

    {
        title: "Civilization VI", 
        id:20, 
        price:500, 
        rating:"/10",
        category:"Estrategia", 
        año:"2016", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2020/08/14/game_cover/768899381597392339.jpg",
        pictureUrl2:'https://s3.gaming-cdn.com/images/products/8579/616x353/sid-meier-s-civilization-vi-pc-mac-juego-steam-cover.jpg?v=1652777620',
        review: "Civilization VI ofrece nuevas maneras de interactuar con tu mundo: ahora las ciudades se expanden físicamente en el mapa, la investigación activa de tecnología y cultura desbloquea nuevos potenciales y los líderes actúan en función de sus rasgos históricos mientras intentas conseguir la victoria de una de las cinco maneras posibles.",
        processor: "4° Generation Intel Core i5 2.5 Ghz or AMD FX8350 4.0 Ghz",
        memory: "8 GB RAM",
        graphics: "2GB & AMD 7970 or nVidia 770",
        storage: "12 GB available space",
    },

    {
        title: "Age of Empires II DE", 
        id:21, 
        price:300, 
        rating:"/10",
        category:"Estrategia", 
        año:"2019", 
        pictureUrl:"https://as01.epimg.net/meristation/imagenes/2019/09/14/game_cover/609478601568448183.jpg",
        pictureUrl2:'https://s3.gaming-cdn.com/images/products/4820/616x353/age-of-empires-ii-definitive-edition-definitive-edition-pc-juego-steam-cover.jpg?v=1650985512',
        review: "Age of Empires II: Definitive Edition para PC es el relanzamiento del clásico de estrategia en tiempo real en su vigésimo aniversario. El juego conserva todo el encanto y la popularidad del original, pero lo combina con veinte años de mejoras en el mundo de los juegos: gráficos de alta definición, jugabilidad y visuales mejorados y cuatro nuevas civilizaciones, así como una nueva campaña para un jugador llamada The Last Khans.",
        processor: "2.4 Ghz i5 or greater or AMD equivalent",
        memory: "8 GB RAM",
        graphics: "Nvidia GTX 650 or AMD HD 5850",
        storage: "30 GB available space",
    },

    {
        title: "Rise of Nations", 
        id:22, 
        price:500, 
        rating:"/10",
        category:"Estrategia", 
        año:"2014", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2016/06/15/game_cover/1465966800.jpg",
        pictureUrl2:'https://s1.gaming-cdn.com/images/products/8619/616x353/juego-steam-rise-of-nations-extended-edition-cover.jpg?v=1617887295',
        review: "Rise of Nations is a real-time strategy game that spans all history. Start with a single city in the Ancient Age; gather resources; build an infrastructure; research technologies; construct Wonders of the World such as the Pyramids and the Eiffel Tower; and expand your military might across the world.",
        processor: "2.6 Ghz",
        memory: "4 GB RAM",
        graphics: "Direct X 11+",
        storage: "5 GB available space",
    },

    {
        title: "StarCraft II", 
        id:23, 
        price:500, 
        rating:"/10",
        category:"Estrategia", 
        año:"2010", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2017/03/09/game_cover/1489078800.jpg",
        pictureUrl2:'https://s2.gaming-cdn.com/images/products/70/616x353/starcraft-2-wings-of-liberty-pc-mac-juego-battlenet-cover.jpg?v=1645181649',
        review: "Starcraft 2: Wings of Liberty es un juego de estrategia en tiempo real de ciencia ficción. También es una secuela: del juego original, de la serie de Brood War y la primera secuela de Starcraft, y ahora también incluye un pack de expansión considerable que se lanzó por partes después del lanzamiento original.",
        processor: "Pentium Dual Core E2220 2.40GHz / Phenom 8250e Triple-Core",
        memory: "2 GB RAM",
        graphics: "GeForce 8800 GTX 768MB / Radeon HD 3870",
        storage: "12 GB available space",
    },

    {
        title: "Northgard", 
        id:24, 
        price:500, 
        rating:"/10",
        category:"Estrategia", 
        año:"2018", 
        pictureUrl:"https://as01.epimg.net//meristation/imagenes/2019/10/04/game_cover/514606711570215073.jpg",
        pictureUrl2:'https://s3.gaming-cdn.com/images/products/1955/616x353/northgard-pc-mac-juego-steam-cover.jpg?v=1649236830',
        review: "Northgard para PC es un juego de estrategia en tiempo real en el que el jugador debe levantar un asentamiento vikingo desde sus humildes comienzos y desarrollarlo hasta convertirse en una civilización poderosa.",
        processor: "Intel i5 3.1 Ghz Quad core",
        memory: "2 GB RAM",
        graphics: "Nvidia GTX 660 / Radeon HD 7800",
        storage: "1 GB available space",
    },
]

export default prodIniciales